### PR TITLE
Fixes for arm64 and Debian Bullseye

### PR DESCRIPTION
**Pull request by marte26**
Made changes to the installers workflow file to make it build working arm64 images.
Switched the sqlite package for the sqlite3 package since it doesn't exist in Debian Bullseye anymore.

### CODE REVIEW

**Comment by trenutoo** [comment]
The oses are not all available for arm64, such as the debian buster. I do not see any java workflow changes, did you forget to push them?

**Comment by marte26** [comment]
The debian:buster-slim image is available for arm64, the java workflow already had the arm64 build but it failed because of the sqlite package

**Comment by trenutoo** [comment]
> The debian:buster-slim image is available for arm64, the java workflow already had the arm64 build but it failed because of the sqlite package

The `debian:buster-slim` is[ hard-coded to amd64](https://github.com/pterodactyl/yolks/blob/master/oses/debian/Dockerfile#L1), as such this change will not do anything to it. You'd have to remove that, and change it to `--platform=$BUILDPLATFORM`

**Comment by marte26** [comment]
Sorry, didn't catch that. I will change it

**Comment by marte26** [comment]
Fixed it

**Review by trenutoo — APPROVED** [review]
LGTM, thank you for the contribution!

**Pull request merged**
