### PR TITLE
Java lsof

### PR DESCRIPTION
**Pull request by roengle**
Update all images for java to include the `lsof` command.

(Originally made for Apache Solr to run)

Apache Solr requires both Java11+ and the `lsof` command installed. From testing, `lsof` does *not* need to be run as root to work.

### CODE REVIEW

**Comment by parkervcp** [comment]
why not just add lsof to all the java eggs?

**Comment by roengle** [comment]
> why not just add lsof to all the java eggs?

I felt it would've been better to not modify every single Java egg, but I could do that.

**Comment by parkervcp** [comment]
If it's something a service might use and it's minimal in size it's good for future proofing.

**Comment by roengle** [comment]
Sounds good, should I just put it in another PR?

**Comment by DaneEveritt** [comment]
Just make the changes in this PR and remove the custom image that was added. 👍🏻

**Comment by roengle** [comment]
Changes made

**Review by parkervcp — APPROVED** [review]
LGTM

**Pull request merged**
