### PR TITLE
Add Java 21

### PR DESCRIPTION
**Pull request by seailz**
new to this so lmk if I've done something wrong haha

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
We do not jusr openjdk base images. And the ones we use do not het have a 21 image.

**Comment by seailz** [comment]
> We do not jusr openjdk base images. And the ones we use do not het have a 21 image.

So how should I proceed with this

**Comment by QuintenQVD0** [comment]
> > We do not jusr openjdk base images. And the ones we use do not het have a 21 image.
> 
> So how should I proceed with this

until eclipse-temurin releases a 21 release notthing

**Comment by finnmargraf** [comment]
Will this PR be updated now that Eclipse-Temurin 21 has been released?
https://hub.docker.com/layers/library/eclipse-temurin/21-jdk-jammy/images/sha256-f6c699c4bb26b7ae068c6447a657ac9209b5e905e7041681316782278aae5ff6?context=explore

**Comment by QuintenQVD0** [comment]
> Will this PR be updated now that Eclipse-Temurin 21 has been released? https://hub.docker.com/layers/library/eclipse-temurin/21-jdk-jammy/images/sha256-f6c699c4bb26b7ae068c6447a657ac9209b5e905e7041681316782278aae5ff6?context=explore

up to the Author,  I made one to Parker repo.

**Comment by finnmargraf** [comment]
> > Will this PR be updated now that Eclipse-Temurin 21 has been released? https://hub.docker.com/layers/library/eclipse-temurin/21-jdk-jammy/images/sha256-f6c699c4bb26b7ae068c6447a657ac9209b5e905e7041681316782278aae5ff6?context=explore
> 
> 
> 
> up to the Author,  I made one to Parker repo.

Yeah, I saw it. I will take whatever gets merged first, probably the parker repo

**Pull request closed without merging**
