### PR TITLE
Add Java 19 (rebased)

### PR DESCRIPTION
**Pull request by PerchunPak**
Rebased version of https://github.com/pterodactyl/yolks/pull/31.

### CODE REVIEW

**Review by PystoyPlayer — COMMENTED** [review]
+++

**Comment by lubaskinc0de** [comment]
please merge it, i need Java 19 for my server, if its not merged before 20th July. i buy other host.

**Comment by rafi67000** [comment]
> please merge it, i need Java 19 for my server, if its not merged before 20th July. i buy other host.

I can give you my java 19 image (or java 20)

**Comment by PerchunPak** [comment]
For those, who are looking for already deployed Java 19 build, use `ghcr.io/parkervcp/yolks:java_19`.

**Review by matthewpi — APPROVED** [review]

**Pull request merged**
